name = "HorizonsEphemeris"
uuid = "05ee1981-f730-42d8-b713-4f42d99733dc"
authors = ["Joe Carpinelli <joseph.d.carpinelli@loopy.software>"]
version = "0.1.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HorizonsAPI = "c15253bb-5e94-4b8b-9a02-579bb6c8e3ce"
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"

[compat]
CSV = "0.10"
HorizonsAPI = "0.1"
DocStringExtensions = "0.9"
SPICE = "0.2"
julia = "1"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
